user  nginx;
worker_processes  auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Основные настройки
    sendfile on;
    keepalive_timeout 65;
    client_max_body_size 100M;

    # Настройки таймаутов
    proxy_connect_timeout 600s;
    proxy_send_timeout 600s;
    proxy_read_timeout 600s;

    server {
        listen 80;
        # server_name 188.120.241.192;
        server_name 188.120.241.192;

        # Перенаправление с HTTP на HTTPS не будет работать без SSL-сертификата для localhost,
        # поэтому мы оставим только HTTP для простоты.

        # Путь к SSL-сертификатам не нужен для localhost без HTTPS.

        location / {
            # proxy_pass http://frontend:80/;
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html;
            
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
        location /api/ {
            proxy_pass http://backend:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }        
    }
}
