export const defaultFonts = [
  "Arial",
  "Verdana",
  "Helvetica",
  "Tahoma",
  "Trebuchet MS",
  "Times New Roman",
  "Georgia",
  "Garamond",
  "Courier New",
  "Brush Script MT",
  "Impact",
  "Comic Sans MS",
  "Palatino Linotype",
  "Lucida Sans Unicode",
  "Lucida Console",
  "Century Gothic",
  "Candara",
  "Franklin Gothic Medium",
  "Gill Sans",
  "Segoe UI",
  "Optima",
  "Book Antiqua",
  "Calibri",
  "Poppins"
];
